import type { Metadata } from "next";
import { Provider as ChakraProvider } from "@/components/ui/provider";
import { ApolloClientProvider } from "@/components/ui/apollo-provider";
import { Container } from "@chakra-ui/react";
import { Outfit } from "next/font/google";
import NavBar from "@/components/shared/Navbar/NavBar";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Aniverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ApolloClientProvider>
          <ChakraProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            <Container>{children}</Container>
          </ChakraProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
