import type { Metadata } from "next";
import { Provider as ChakraProvider } from "@/components/ui/provider";
import { ThemeProvider } from "next-themes";
import { ApolloClientProvider } from "@/components/ui/apollo-provider";
import NavBar from "@/components/shared/Navbar/NavBar";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Aniverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ApolloClientProvider>
            <ChakraProvider>
              <Container>
                <NavBar />
                {children}
              </Container>
            </ChakraProvider>
          </ApolloClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
