import type { Metadata } from "next";
import { Provider as ChakraProvider } from "@/components/ui/provider";
import { ThemeProvider } from "next-themes";
import { ApolloClientProvider } from "@/components/ui/apollo-provider";

export const metadata: Metadata = {
  title: "Aniverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ApolloClientProvider>
          <ChakraProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ChakraProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
